Don't tell readthedocs to install versioneer
I'm getting a somewhat opaque error building the docs:
raise CalledProcessError(retcode, process.args,
                                 output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command 'python -c 'import versioneer; print(versioneer.get_version())'' returned non-zero exit status 1.

However, when I compare to bagofholding -- which already uses hatch and builds its docs fine -- I can see that this line has been removed from the .readthedocs.yml config. So for now let's be very practical and just try synchronizing with what's already working.

Signed-off-by: liamhuber <liamhuber@greyhavensolutions.com>